# /etc/greetd/config.toml

[terminal]
# The VT to run the greeter on.
# Can be "/dev/ttyX" or just "X" (integer)
vt = 1

# The default session, also known as the greeter.
[default_session]
# `agreety` is the default greeter. Use `gtkgreet` with `cage` instead.
# command = "agreety --cmd $SHELL"
command = "cage -s -- gtkgreet" # Use cage to run gtkgreet, -s enables VT switching

# The user to run the command as.
The user needs to be root or have permission to start Wayland/X sessions.
# user = "greeter" 